# Generated by Django 4.1.7 on 2023-03-23 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='city',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
