# Generated by Django 4.1.7 on 2023-03-23 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_comment_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='test',
            field=models.CharField(default='test', max_length=300),
            preserve_default=False,
        ),
    ]
