# Generated by Django 4.1.7 on 2023-03-23 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_comment_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='test',
        ),
    ]
