# Generated by Django 4.1.7 on 2023-03-29 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_remove_comment_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='yelpId',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
